
CREATE TABLE IF NOT EXISTS USER(
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    user_nickname VARCHAR(64) NOT NULL UNIQUE,
    user_email VARCHAR(64) NOT NULL UNIQUE,
    user_password VARCHAR(64) NOT NULL

    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 
);